import {StyleSheet} from 'react-native';

export const getStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 20,
      backgroundColor: theme.backgroundColor,
    },
    modalContainer: {
      width: '80%',
      backgroundColor: theme.modalBackgroundColor,
      padding: 20,
      justifyContent: 'center',
      borderRadius: 10,
      alignSelf: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
      opacity: 1,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.modalOverlayColor,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 15,
      color: theme.textColor,
      textAlign: 'center',
    },
    modalDescription: {
      fontSize: 16,
      marginBottom: 10,
      color: theme.secondaryTextColor,
      textAlign: 'center',
    },
    modalDate: {
      fontSize: 14,
      marginBottom: 20,
      color: theme.secondaryTextColor,
      textAlign: 'center',
    },
    input: {
      height: 40,
      borderColor: theme.inputBorderColor || '#333333',
      borderWidth: 1,
      borderRadius: 8,
      marginBottom: 10,
      paddingHorizontal: 10,
      backgroundColor: theme.inputBackgroundColor,
      color: theme.inputTextColor,
    },
    button: {
      backgroundColor: theme.buttonBackgroundColor,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 10,
    },
    dateButton: {
      backgroundColor: theme.buttonDateBackgroundColor,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 10,
    },
    buttonText: {
      color: theme.buttonTextColor,
      fontWeight: 'bold',
      fontSize: 16,
    },
    addButton: {
      position: 'absolute',
      bottom: 30,
      right: 30,
      backgroundColor: theme.buttonBackgroundColor,
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: 'center',
      alignItems: 'center',
    },
    addButtonText: {
      color: theme.buttonTextColor,
      fontSize: 24,
      fontWeight: 'bold',
    },
  });

export const lightTheme = {
  backgroundColor: '#FFFFFF',
  textColor: '#000000',
  inputBackgroundColor: '#F5F5F5',
  inputTextColor: '#000000',
  inputBorderColor: '#CCCCCC',
  buttonBackgroundColor: '#FF5722',
  buttonTextColor: '#FFFFFF',
  modalBackgroundColor: '#FFFFFF',
  modalOverlayColor: 'grey',
  secondaryTextColor: '#666666',
  buttonDateBackgroundColor: '#CCCCCC',
};

export const darkTheme = {
  backgroundColor: '#121212',
  textColor: '#FFFFFF',
  inputBackgroundColor: '#1E1E1E',
  inputTextColor: '#FFFFFF',
  inputBorderColor: '#444444',
  buttonBackgroundColor: '#FF5722',
  buttonTextColor: '#FFFFFF',
  modalBackgroundColor: '#1E1E1E',
  modalOverlayColor: 'rgba(0, 0, 0, 1)',
  secondaryTextColor: '#AAAAAA',
  buttonDateBackgroundColor: '#CCCCCC',
};
